// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwwttfespwukpyxfuazi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3d3R0ZmVzcHd1a3B5eGZ1YXppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NDkxNjAsImV4cCI6MjA2MTMyNTE2MH0.SMRCgHXbq8oKNpQFuAL80FWzqscdPGGbxzet_XwH50E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);